version: '3.8'

services:
  # PostgreSQL数据库服务
  postgres:
    image: postgres:15
    container_name: langchain_postgres
    restart: always
    environment:
      POSTGRES_USER: langchain_user
      POSTGRES_PASSWORD: langchain_password
      POSTGRES_DB: langchain_chat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - langchain_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langchain_user -d langchain_chat"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin管理工具（可选）
  pgadmin:
    image: dpage/pgadmin4
    container_name: langchain_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - langchain_network
    depends_on:
      - postgres

networks:
  langchain_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: